### PR TITLE
DLGetEntries test fit new method and fix ContactNameException

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by gamerson** [comment]
Test is failing

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! d25d54f...7c71ed7 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by AndyWu2015** [comment]
fixes https://github.com/gamerson/blade.tools/issues/16

**Pull request closed without merging**
