### PR TITLE
[migrator] added DLAppHelpereLocalService move functions migrator fixes #47

### LINKED ISSUE #47: Removed Sync Logic from DLAppHelperLocalService Methods
Date: 2014-Sep-05
https://issues.liferay.com/browse/LPS-48895
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#removed-sync-logic-from-dlapphelperlocalservice-methods

### PR DESCRIPTION
**Pull request by jtydhr88**
…

### CODE REVIEW

**Comment by jtydhr88** [comment]
[migrator] added DLAppHelpereLocalService move functions migrator fixes #47

**Comment by gamerson** [comment]
Can you move these migration checks to the existing DLAppHelperLocalService util that I already merged?  Just to reuse those other test/component classes.  thanks.

**Comment by jtydhr88** [comment]
@gamerson they are two different cases. We have set the the properties like title, url for the delete case. How can we use the same class for checking both move functions and delete function, and the properties are different at the same time?

**Comment by gamerson** [comment]
In the existing component in the 
```
@Override
    protected List<SearchResult> searchJavaFile(File file) {
```

method you can search for multiple method names.  So you can search for both move and delete.

For properties we will need it to be a separate component.

**Pull request closed without merging**
