### PR TITLE
[migrator] add param mapping feature in findMethodInvocation and fixe…

### PR DESCRIPTION
**Pull request by AndyWu2015**
…s #50

### CODE REVIEW

**Comment by AndyWu2015** [comment]
This time I run command line "gradle clean build" on my machine and succeed .

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Here is the error : java.lang.AssertionError: expected:<201> but was:<207>
 at org.junit.Assert.fail(Assert.java:88)
 at org.junit.Assert.failNotEquals(Assert.java:743)
 at org.junit.Assert.assertEquals(Assert.java:118)
 at org.junit.Assert.assertEquals(Assert.java:555)
 at org.junit.Assert.assertEquals(Assert.java:542)
 at blade.migrate.test.AllProblemsTest.allProblems(AllProblemsTest.java:27)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
 at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
 at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
 at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
 at junit.framework.TestSuite.runTest(TestSuite.java:255)
 at junit.framework.TestSuite.run(TestSuite.java:250)
 at aQute.junit.Activator.test(Activator.java:325)
 at aQute.junit.Activator.automatic(Activator.java:208)
 at aQute.junit.Activator.run(Activator.java:142)
 at aQute.launcher.Launcher$5.call(Launcher.java:1198)
 at aQute.launcher.Launcher$5.call(Launcher.java:1196)
 at aQute.launcher.Launcher.run(Launcher.java:278)
 at aQute.launcher.Launcher.main(Launcher.java:87)


This is what I get on my machine.  That means that something is wrong with your branch, either it is not up2date or something wrong with your repo like bad lineendings or something.  

try using ```./gradlew clean build``` and let me know what happens.  Also have someone else one windows try it and also have someone else with Linux (ashley or terry) try it and see what they get.  It is likely something on your machine that we need to fix.

**Comment by gamerson** [comment]
Please send your new pull request on top of this one <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/AndyWu2015/blade.tools/pull/1. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
