### PR TITLE
BDE-36 Replaced the ReservedUserScreenNameException

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by gamerson** [comment]
Check the build, it is failling on this pull.  You can run it locally with "gradle build"

**Comment by simonjhy** [comment]
Greg, I run junit test in local, it no error.
replacereserveruserscrrennameexception

**Comment by gamerson** [comment]
So you will need to run it from command line. Just in the top level run
gradle build

Also you can run the osgi test from the test bundle. Right click the test
bundle and select Run as osgi Junit test

On Sunday, July 5, 2015, simon.jiang <notifications@github.com> wrote:

> Greg, I run junit test in local, it no error.
> [image: replacereserveruserscrrennameexception]
> <https://cloud.githubusercontent.com/assets/5745444/8515502/618ea0d4-23d6-11e5-9a68-0625681cde9f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/blade.tools/pull/96#issuecomment-118707525>.
>


-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by simonjhy** [comment]
I have run the gradle build on command line. But it shows the error isn't related to this change. So I didn't clear what's error are related to this issue.
replacereserveruserscrrennameexception

**Pull request closed without merging**
