### PR TITLE
[migrator] improve JspFileChecker to find attribute value

### PR DESCRIPTION
**Pull request by lovettli**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
@lovettli  please read all of my code changes here to understand the changes: 329a4b2...5abd7be

**Comment by lovettli** [comment]
Yes, i can understand all of your code changes. That's right we need to add some validation code of tagName and number of attrValue.  
I have a question about AllJSPTagProblemsTest.java .Yeah, we have AllProblemsTest.java that it can test all the problem in this folder "../blade.migrate.liferay70/projects/". we create a separate test file for all JSP testss. 
In normal logic i add a new JSPTagMigrator and JUnit test file to test problem in this folder "blade.migrate.test/jsptests/" . It should not affect problem number of AllProblemTest file. Because they haven't some relationship.
But affect show in my this commit cause test failure of AllProblemTest number.  Because this tag
 ```
<%@ taglib uri="http://alloy.liferay.com/tld/aui" prefix="aui" %>
 ```
not only show in "../blade.migrate.liferay70/projects/" folder but also in here "blade.migrate.test/jsptests/" .
Now no matter which folder we test, our project will use all of migrators to test this file. If target code show in both of test folder, AllProblemTest will be fail.So AllJSPTagProblemsTest did not really separate test content. i just feel a little bit logic confuse.
What do you think ?

**Comment by gamerson** [comment]
So I updated the logic of the findJspTags code, to correctly match
attribute names.  Also I found that there was a very small error that lead
to incorrect results.  See this commit:

https://github.com/gamerson/blade.tools/commit/36c2775fee0b629d692b841ad32256e69b2ae63d

We must always remember to release IDOMModel objects when we call
read/write.

On Thu, Sep 17, 2015 at 11:18 PM, Lovett Li <notifications@github.com>
wrote:

> Yes, i can understand all of your code changes. That's right we need to
> add some validation code of tagName and number of attrValue.
>
> I have a question about AllJSPTagProblemsTest.java .Yeah, we have
> AllProblemsTest.java that it can test all the problem in this folder
> "../blade.migrate.liferay70/projects/". we create a separate test file for
> all JSP testss.
> In normal logic i add a new JSPTagMigrator and JUnit test file to test
> problem in this folder "blade.migrate.test/jsptests/" . It should not
> affect problem number of AllProblemTest file. Because they haven't some
> relationship.
> But affect show in my this commit cause test failure of AllProblemTest
> number. Because this tag
>
> <%@ taglib uri="http://alloy.liferay.com/tld/aui" prefix="aui" %>
>
> not only show in "../blade.migrate.liferay70/projects/" folder but also in
> here "blade.migrate.test/jsptests/" .
> Now no matter which folder we test, our project will use all of migrators
> to test this file. If target code show in both of test folder,
> AllProblemTest will be fail.So AllJSPTagProblemsTest did not really
> separate test content. i just feel a little bit logic confuse.
> What do you think ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/blade.tools/pull/217#issuecomment-141339491>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Pull request closed without merging**
