### PR TITLE
[migrator] add AssertPreviewTags and fixes #25

### LINKED ISSUE #25: Changed the Usage of Asset Preview
Date: 2015-Mar-16
https://issues.liferay.com/browse/LPS-53972
https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#changed-the-usage-of-asset-preview

type:java,jsp

### PR DESCRIPTION
**Pull request by lovettli**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
See my comment about NPEs <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Hey Lovett,

When I run this I see lots and lots of stacktraces here:

java.lang.NullPointerException
at
blade.migrate.core.JSPFileChecker.createJSPTranslation(JSPFileChecker.java:43)
at blade.migrate.core.JSPFileChecker.getTranslation(JSPFileChecker.java:127)
at blade.migrate.core.JSPFileChecker.<init>(JSPFileChecker.java:31)
at
blade.migrate.core.JSPTagsFileMigrator.analyzeFile(JSPTagsFileMigrator.java:31)
at
blade.migrate.provider.ProjectMigrationService$1.visitFile(ProjectMigrationService.java:144)
at
blade.migrate.provider.ProjectMigrationService$1.visitFile(ProjectMigrationService.java:123)
at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:135)
at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)


Can you check it on your side?

On Mon, Aug 3, 2015 at 8:52 PM, Lovett Li <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/gamerson/blade.tools/pull/184
> Commit Summary
>
>    - [migrator] add AssertPreviewTags and fixes #25
>
> File Changes
>
>    - *M*
>    blade.migrate.liferay70/src/blade/migrate/core/JSPFileChecker.java
>    <https://github.com/gamerson/blade.tools/pull/184/files#diff-0> (2)
>    - *A*
>    blade.migrate.liferay70/src/blade/migrate/liferay70/AssetPreviewTags.java
>    <https://github.com/gamerson/blade.tools/pull/184/files#diff-1> (31)
>    - *A* blade.migrate.test/jsptests/asset-preview/AssetPreviewTest.jsp
>    <https://github.com/gamerson/blade.tools/pull/184/files#diff-2> (27)
>    - *A*
>    blade.migrate.test/src/blade/migrate/test/AssetPreviewTagsTest.java
>    <https://github.com/gamerson/blade.tools/pull/184/files#diff-3> (50)
>
> Patch Links:
>
>    - https://github.com/gamerson/blade.tools/pull/184.patch
>    - https://github.com/gamerson/blade.tools/pull/184.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/blade.tools/pull/184>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by lovettli** [comment]
ok , i check it right now.

**Pull request closed without merging**
